name: Build and push a container with Jib
on: push

jobs:
  jib:
    name: Jib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build and push container
        run: |
          ./gradlew jib \
              -Djib.to.image=ghcr.io/hhiroshell/cowweb-go/cowweb:latest \
              -Djib.to.tags=latest \
              -Djib.to.auth.username=${{ github.actor }} \
              -Djib.to.auth.password=${{ secrets.CR_PAT }}
