name: Build and push a container with Jib
on: push

jobs:
  jib:
    name: Jib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build and push container
        run: |
          ./gradlew jib \
              -Djib.to.image=ghcr.io/hhiroshell/cowweb-go/cowweb:latest \
              -Djib.to.tags=latest \
              -Djib.to.auth.username=${{ github.actor }} \
              -Djib.to.auth.password=${{ secrets.CR_PAT }}
